### ISSUE TITLE
Implementing a custom language

### ISSUE THREAD

**Issue by charliearaya** [cksource/ckeditor4-plugin-a11ychecker#265]
Hi, I would love to use this tool in other languages. I've done some search but can't seem to find support for other languages. I tried creating new files for Swedish but I wasnt able to make the tool  to use swedish as a language. I created/changed these files:
- lang\sv.js
- quickfix\sv\**.js
- libs\quail\test.json (Added texts for "sv")

Is there anything else I'm missing?

**Comment by mlewand** [comment]
As far as I can see you did most of the job. Last thing I'm missing is [making sure it's enumerated in `plugin.js`  too](https://github.com/cksource/ckeditor4-plugin-a11ychecker/blob/41efb0b3fb108e098c817d391a4e16e6076d9bd8/plugin.js#L18).

You can take a look on [commit where we added German language](https://github.com/cksource/ckeditor4-plugin-a11ychecker/commit/41efb0b3fb108e098c817d391a4e16e6076d9bd8#diff-5fed3e86fc0028cf521b2191b2a152f8) as a reference.

**Comment by mlewand** [comment]
Since there are no further questions I assume the description is clear enough.

**Comment by charliearaya** [comment]
> Since there are no further questions I assume the instruction is clear enough.

Yeah thanks I'll check it out!
